In [ ]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)


In [11]:
#1.Answers:
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

#  Convert X into a DataFrame with custom column names
X_df = pd.DataFrame(X, columns=['feature_1', 'feature_2'])

y_df = pd.Series(y, name='target')


rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X_df, y_df)

selected_features = X_df.columns[rfe.support_].tolist()  

print("Selected features:",selected_features)




Selected features: ['feature_2']


In [ ]:
#2.
from sklearn.feature_selection import VarianceThreshold

X = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)


In [22]:
#2.Answers
from sklearn.feature_selection import VarianceThreshold
import numpy as np

X = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
selector = VarianceThreshold(threshold=0.1)
##X_new = selector.fit_transform(X)

try:
    X_new = selector.fit_transform(X)
except ValueError as e:
    print(f"Skipping selection: {e}")

    X_new = np.array(X) 
    

Skipping selection: No feature in X meets the variance threshold 0.10000


In [ ]:
#3.
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [0, 0, 0]]
similarity = cosine_similarity(data)


In [25]:
#3.Answers:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [0, 0, 0]]
data_np=np.array(data)
print(data_np)

cleaned_data=data_np[~np.all(data_np==0, axis=1)]

similarity = cosine_similarity(cleaned_data)
similarity


[[5 0 3]
 [0 0 0]]


array([[1.]])

In [ ]:
#4.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)


In [30]:
#4.Answers

from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

x=pd.DataFrame(X, columns=['feature1','feature2'])

selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)

selected_features = selector.get_feature_names_out(input_features=x.columns)
print("Selected features:" ,list(selected_features) )

Selected features: ['feature2']


In [ ]:
#5.
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rate': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rating')


In [33]:
#5.Answers

data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rate': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rate')
pivot

item,I1,I2
user,,
A,5.0,3.0
B,NaN,4.0


In [ ]:
#6.
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=3)
X_new = pca.fit_transform(X)


In [38]:
#6.Answers

from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=2)
X_new = pca.fit_transform(X)
print(X_new)

[[-1.41421356  0.        ]
 [ 1.41421356  0.        ]]


In [ ]:
#7.
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
sim = cosine_similarity(ratings.T)


In [43]:
#7.Answers
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})

ratings_filled = ratings.fillna(0)
sim = cosine_similarity(ratings_filled.T)
sim

array([[1.        , 0.        , 0.38348249],
       [0.        , 1.        , 0.89442719],
       [0.38348249, 0.89442719, 1.        ]])

In [ ]:
#8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


In [45]:
#8.Answers    ##NO CHANGE IS REQUIRED
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)

Predicted Score: 2.5


In [ ]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


In [ ]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)

In [55]:
#9.ANSWER
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])

model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=3)
print(indices)

[[0 2 1]]


In [ ]:
#10.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1])
b = np.array([0, 1, 1])

sim = cosine_similarity(a, b)
print("Similarity:", sim)

In [57]:
#10.Answer

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([[1, 0, 1]])
b = np.array([[0, 1, 1]])

sim = cosine_similarity(a, b)
print("Similarity:", sim)

Similarity: [[0.5]]
