In [ ]:
#1. Why does this feature selection with chi2 fail?
from sklearn.feature_selection import SelectKBest, chi2

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)

In [66]:
#1. Answer:

from sklearn.feature_selection import SelectKBest, chi2

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]


X = np.abs(X)

print(X)

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)
X_new


[[1 2 3]
 [4 0 6]
 [7 8 9]
 [1 2 3]]


array([[1, 2],
       [4, 0],
       [7, 8],
       [1, 2]])

In [ ]:
#2.
from sklearn.metrics.pairwise import cosine_similarity

# Error: strings instead of numerical features
user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']

similarity = cosine_similarity([user1], [user2])


In [19]:
#2. Answer:

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer

# Error: strings instead of numerical features
user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']

mlb = MultiLabelBinarizer()
numerical_matrix = mlb.fit_transform([user1, user2])

# Extract the individual 1D numerical arrays
user1_numeric = numerical_matrix[0]
user2_numeric = numerical_matrix[1]

similarity = cosine_similarity([user1_numeric],[user2_numeric])
similarity

array([[0.66666667]])

In [21]:
#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=5)  # more components than features
X_new = pca.fit_transform(X)


In [69]:
#3.Answer

from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=2)  # more components than features
X_new = pca.fit_transform(X)
X_new

array([[-2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.82842712,  0.        ]])

In [ ]:
#4.

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])

similarity = cosine_similarity(ratings)

In [70]:
#4.Answer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])

##Replace Nan

ratings_clean = np.nan_to_num(ratings, nan=0.0)


similarity = cosine_similarity(ratings_clean)
similarity


array([[1.        , 0.68599434],
       [0.68599434, 1.        ]])

In [ ]:
#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

selector = RFE(estimator=LogisticRegression(), n_features_to_select=5)
selector.fit(X, y)  # Error: X and y not defined


In [31]:
#5.Answer

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2, 3], [4, 0, 6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = RFE(estimator=LogisticRegression(), n_features_to_select=3)
selector.fit(X, y)  # Error: X and y not defined


RFE(estimator=LogisticRegression(), n_features_to_select=3)

In [ ]:
#6.from sklearn.metrics.pairwise import cosine_similarity

items = ["action movie", "romantic comedy", "sci-fi thriller"]
similarity = cosine_similarity([items[0]], [items[1]])


In [38]:
#6. Answer

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer
items = ["action movie", "romantic comedy", "sci-fi thriller"]

mlb = MultiLabelBinarizer()
items = mlb.fit_transform([items])

#items[0]


similarity = cosine_similarity([items[0]])

similarity

array([[1.]])

In [ ]:
#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)


In [71]:
#7.Answer

from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0,1,1]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)
X_new

array([[2],
       [4],
       [6]])

In [ ]:
#8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5, 4, 3])
cosine_similarity(ratings, ratings)


In [45]:
#8.Answer

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([[5, 4, 3]])
cosine_similarity(ratings, ratings)

array([[1.]])

In [ ]:
#9.
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)


In [59]:
#9.Answer:

from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2
import numpy as np

X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]

# For nested list, Loop through each sublist and replace None with 0
X = [[0 if item is None else item for item in sublist] for sublist in X]

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)


Pipeline(steps=[('select',
                 SelectKBest(k=1,
                             score_func=<function chi2 at 0x7fbabcc4ab80>))])

In [ ]:
#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [68]:
#10.Answer:

from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

# Apply absolute value to the underlying non-zero data
X.data = np.abs(X.data)

print(X.toarray())

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)

[[0 1 3]
 [0 2 1]
 [3 1 0]]
