In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read movie dataset

i_cols= ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

items = pd.read_csv( 'ml-100k/u.item',sep='|',names=i_cols, encoding='latin-1' )

In [3]:
items.head(2)

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0


In [4]:
#Select only needed columns for item

movie_content=items[['movie id', 'movie title' ,'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

movie_content


,movie id,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0


In [5]:
# Create movie Vector

movie_vec=items[['Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

movie_vec

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0


In [6]:
# Rename the index from RangeIndex(start=0, stop=1682, step=1) to RangeIndex(start=1, stop=1683, step=1)
movie_vec.index=range(1,1683)

In [7]:
movie_vector=movie_vec.T
movie_vector

,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
Action,0,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Adventure,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Animation,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Children's,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Comedy,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
Crime,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documentary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Drama,0,0,0,1,1,1,1,1,1,1,...,0,1,1,1,1,1,0,1,0,1
Fantasy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Film-Noir,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [8]:
#Read the ratings dataset
r_cols= ['user_id', 'movie_id', 'rating', 'unix_timestamp']

ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')
ratings

,user_id,movie_id,rating,unix_timestamp
0,196,242,3,881250949
1,186,302,3,891717742
2,22,377,1,878887116
3,244,51,2,880606923
4,166,346,1,886397596
...,...,...,...,...
99995,880,476,3,880175444
99996,716,204,5,879795543
99997,276,1090,1,874795795
99998,13,225,2,882399156


In [9]:
## Create the content vector(user_vector and Item Vector)

In [10]:
# check for user = 1
u1=ratings[ratings['user_id']==1][['movie_id','rating']]

In [11]:
u1

,movie_id,rating
202,61,4
305,189,3
333,33,4
334,160,4
478,20,4
...,...,...
92049,28,4
92487,172,5
94019,122,3
96699,152,5


In [12]:
## Create content list for the user using movie vector
u1_list=[]
for i in u1['movie_id']:
    f=movie_vector[i].values
    u1_list.append(f)

In [13]:
u1_list

[array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,

In [14]:
# Converting content list in dataframe

uu1=pd.DataFrame(u1_list,columns=range(1,19))
uu1

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
268,1,1,0,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0
269,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
270,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0


In [15]:
# Create single vector for single user
vec=[]
for j in range(1,19):
    vec.append(sum(uu1[j])/272)
vec

[0.2757352941176471,
 0.15441176470588236,
 0.04411764705882353,
 0.09191176470588236,
 0.33455882352941174,
 0.09191176470588236,
 0.01838235294117647,
 0.39338235294117646,
 0.007352941176470588,
 0.003676470588235294,
 0.04779411764705882,
 0.04779411764705882,
 0.01838235294117647,
 0.16176470588235295,
 0.15808823529411764,
 0.19117647058823528,
 0.09191176470588236,
 0.022058823529411766]

In [16]:
##Creating user vector for all users

def users_vector(ratings,movie_vector):
    vector=[]
    for user in range(1,944):
        u1=ratings[ratings['user_id']==user][['movie_id','rating']]
        ## Create content list for the user using movie vector
        u1_list=[]
        for i in u1['movie_id']:
            f=movie_vector[i].values
            u1_list.append(f)
        uu1=pd.DataFrame(u1_list,columns=range(1,19))
        vec=[]
        for j in range(1,19):
            vec.append(sum(uu1[j])/len(u1)) ## Summ up all genre and divide it by no of movie ids
        vector.append(vec)
    return vector   

In [17]:
vector=users_vector(ratings,movie_vector)
vector

[[0.2757352941176471,
  0.15441176470588236,
  0.04411764705882353,
  0.09191176470588236,
  0.33455882352941174,
  0.09191176470588236,
  0.01838235294117647,
  0.39338235294117646,
  0.007352941176470588,
  0.003676470588235294,
  0.04779411764705882,
  0.04779411764705882,
  0.01838235294117647,
  0.16176470588235295,
  0.15808823529411764,
  0.19117647058823528,
  0.09191176470588236,
  0.022058823529411766],
 [0.16129032258064516,
  0.04838709677419355,
  0.016129032258064516,
  0.06451612903225806,
  0.25806451612903225,
  0.14516129032258066,
  0.0,
  0.5645161290322581,
  0.016129032258064516,
  0.03225806451612903,
  0.03225806451612903,
  0.016129032258064516,
  0.06451612903225806,
  0.25806451612903225,
  0.06451612903225806,
  0.1935483870967742,
  0.04838709677419355,
  0.0],
 [0.25925925925925924,
  0.07407407407407407,
  0.0,
  0.0,
  0.2222222222222222,
  0.18518518518518517,
  0.018518518518518517,
  0.4074074074074074,
  0.0,
  0.037037037037037035,
  0.0925925925925

In [18]:
## Converting it into dataset

users_vector=pd.DataFrame(vector)
users_vector

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.275735,0.154412,0.044118,0.091912,0.334559,0.091912,0.018382,0.393382,0.007353,0.003676,0.047794,0.047794,0.018382,0.161765,0.158088,0.191176,0.091912,0.022059
1,0.161290,0.048387,0.016129,0.064516,0.258065,0.145161,0.000000,0.564516,0.016129,0.032258,0.032258,0.016129,0.064516,0.258065,0.064516,0.193548,0.048387,0.000000
2,0.259259,0.074074,0.000000,0.000000,0.222222,0.185185,0.018519,0.407407,0.000000,0.037037,0.092593,0.037037,0.203704,0.092593,0.148148,0.388889,0.092593,0.000000
3,0.333333,0.166667,0.000000,0.000000,0.166667,0.166667,0.041667,0.250000,0.000000,0.000000,0.041667,0.041667,0.208333,0.125000,0.250000,0.458333,0.083333,0.000000
4,0.320000,0.188571,0.080000,0.165714,0.468571,0.051429,0.000000,0.154286,0.011429,0.005714,0.160000,0.068571,0.017143,0.108571,0.188571,0.108571,0.080000,0.011429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.367347,0.204082,0.020408,0.020408,0.306122,0.061224,0.000000,0.367347,0.020408,0.000000,0.020408,0.020408,0.020408,0.204082,0.163265,0.244898,0.061224,0.000000
939,0.214953,0.112150,0.018692,0.046729,0.392523,0.065421,0.000000,0.448598,0.000000,0.028037,0.037383,0.065421,0.028037,0.224299,0.177570,0.186916,0.140187,0.000000
940,0.454545,0.318182,0.136364,0.090909,0.318182,0.045455,0.000000,0.227273,0.000000,0.000000,0.000000,0.045455,0.045455,0.045455,0.363636,0.318182,0.045455,0.000000
941,0.227848,0.139241,0.050633,0.164557,0.278481,0.000000,0.000000,0.392405,0.025316,0.012658,0.037975,0.063291,0.113924,0.215190,0.075949,0.253165,0.126582,0.037975


In [19]:
# Check user vector shape
users_vector.shape

(943, 18)

In [20]:
# Check movie vector shape
movie_vector.shape

(18, 1682)

In [21]:
# Dot matrix of user vector and movie vector
content_vector=np.dot(users_vector,movie_vector)

In [22]:
#Convert into dataframe
content_vector=pd.DataFrame(content_vector)
content_vectors=content_vector.T

In [23]:
content_vectors

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,0.470588,0.338710,0.222222,0.166667,0.714286,0.454976,0.339950,0.220339,0.272727,0.336957,...,0.482759,0.282051,0.373239,0.375,0.518519,0.346939,0.457944,0.545455,0.493671,0.398810
1,0.621324,0.403226,0.722222,0.958333,0.617143,0.336493,0.570720,1.254237,0.545455,0.396739,...,0.482759,0.871795,0.478873,0.325,0.777778,0.816327,0.514019,1.090909,0.620253,0.797619
2,0.191176,0.193548,0.388889,0.458333,0.108571,0.113744,0.191067,0.305085,0.227273,0.184783,...,0.120690,0.282051,0.197183,0.100,0.296296,0.244898,0.186916,0.318182,0.253165,0.208333
3,1.003676,0.983871,0.888889,0.750000,0.942857,0.924171,0.816377,1.118644,0.954545,0.831522,...,0.971264,1.076923,1.007042,1.075,0.990741,1.040816,1.056075,1.000000,0.898734,1.053571
4,0.676471,0.903226,0.981481,0.875000,0.314286,0.672986,0.632754,0.745763,0.727273,0.711957,...,0.563218,0.820513,0.767606,0.775,0.648148,0.673469,0.700935,0.590909,0.645570,0.654762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.393382,0.564516,0.407407,0.250000,0.154286,0.492891,0.362283,0.288136,0.500000,0.440217,...,0.390805,0.461538,0.478873,0.625,0.296296,0.367347,0.448598,0.227273,0.392405,0.339286
1678,0.352941,0.451613,0.481481,0.583333,0.217143,0.308057,0.330025,0.423729,0.590909,0.380435,...,0.327586,0.589744,0.415493,0.325,0.490741,0.448980,0.411215,0.363636,0.468354,0.404762
1679,0.555147,0.822581,0.500000,0.375000,0.262857,0.687204,0.501241,0.406780,0.863636,0.635870,...,0.597701,0.769231,0.697183,0.850,0.490741,0.571429,0.672897,0.272727,0.607595,0.535714
1680,0.334559,0.258065,0.222222,0.166667,0.468571,0.312796,0.218362,0.169492,0.272727,0.255435,...,0.362069,0.230769,0.338028,0.300,0.370370,0.306122,0.392523,0.318182,0.278481,0.333333


In [24]:
content_vectors.to_csv('content_vectors.csv',index=False)

In [25]:
def contentbased_vector(ratings,content_vectors,user_id,threshold):
    u2=ratings[ratings['user_id']==user_id]['movie_id'].values
    val=content_vectors[content_vectors[user_id]>(content_vectors[user_id].max()-threshold)]
    ##print(val)
    recom=[]
    for i in val.index:
        if(i in u2):
            pass
        else:
            recom.append(i)
    return recom

In [27]:
contentbased_vector(ratings,content_vectors,4,0.2)

[20, 183, 200, 256, 559]